=== angelsaez10/AngelSaezLazaroHTML/Xsd/ejemplo2xsd/ejemplo1simple21.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="elementos">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="elemento" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="nombre" type="xs:string" />
							<xs:element name="color" type="xs:string" />
							<xs:element name="masa" type="xs:string" />
						</xs:sequence>
						<xs:attribute name="codigo" use="required" />
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== angelsaez10/AngelSaezLazaroHTML/Xsd/ejemplo2xsd/ejemplo1simple2.xml
<?xml version="1.0" encoding="UTF-8"?>
<elementos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="ejemplo1simple21.xsd" >
    <elemento codigo="e01">
		<nombre>Agua</nombre>
		<color>Azul</color>
		<masa>234.5</masa>
	</elemento>
	<elemento codigo="e02">
		<nombre>Fuego</nombre>
		<color>Rojo</color>
		<masa>1234.5</masa>
	</elemento>
</elementos>
