=== angelsaez10/AngelSaezLazaroHTML/Xsd/ejemplo2xsd/personas.dtd
<!ELEMENT personas (persona)+ >
<!ENTITY rsa "República Sudafricana">
<!ENTITY eeuu "Estados Unidos">
<!ENTITY spa "España">
<!ELEMENT persona (nombrep, edad, password, sueldo) >
<!ATTLIST persona
            dni CDATA #REQUIRED
            micolor (rojo|azul|amarillo|verde) #REQUIRED
            pais ENTITY>
<!-- Chapuza: convertimos el elemento micolor a un atributo
     para que pueda tener una lista de valores posibles -->

<!ELEMENT nombrep (#PCDATA)>
<!ELEMENT edad (#PCDATA)>
<!ELEMENT password (#PCDATA)>
<!ELEMENT sueldo (#PCDATA)>

=== angelsaez10/AngelSaezLazaroHTML/Xsd/ejemplo2xsd/personas2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- personas2.xml NO ES igual que personas.xml
     porque hay "diferencias" -->
<!DOCTYPE personas SYSTEM "personas.dtd">
<personas>
  <persona dni="12345678A" micolor="rojo" pais="&eeuu;">
	<nombrep>Miguel Martín</nombrep>
    <edad>37</edad>
    <password>abcdef33</password>
    <sueldo>1500.75</sueldo>
</persona>

<persona dni="33445566M" micolor="azul" pais="&spa;">
	<nombrep>María García</nombrep>
    <edad>31</edad>
    <password>pepito22</password>
    <sueldo>1850.00</sueldo>
</persona>

</personas>
